### PR TITLE
Created folders "v1" and "v2"

### PR DESCRIPTION
**Pull request by CrystalBallBe**
I created the folders "v1" and "v2".
To archive all the files (except `LICENSE` and `README.md`), I moved those files to the folder "v1".
And I copied those files and placed them in the folder "v2".
As a result, the contents of the two folders now match exactly. 

I intend to update the files under "v2".

### CODE REVIEW

**Comment by MicahZoltu** [comment]
It has been a while since I have done GitHub pages, but I think we'll need an index file in the root that links out to the v1 and v2 docs at the least.  An alternative option would be to have two branches' and then we can point GH Pages at one vs the other.

**Comment by CrystalBallBe** [comment]
Sorry, this pull request change definitely breaks the file structure for GitHub Page. I just started learning GitHub page. 

> I think we'll need an index file in the root that links out to the v1 and v2 docs at the least. An alternative option would be to have two branches' and then we can point GH Pages at one vs the other.

I prefer the former but I'm not sure how to do it. It seems to me that the latter is easier to implement.

**Comment by msagansk** [comment]
Yeah it's been a while since I've looked at how Github Pages works, but this will probably break it. So I won't merge it for now if that's ok?

**Comment by CrystalBallBe** [comment]
Yes, I'm closing this pull request. Sorr for making a noise.
I will try to create an index file in the root that links out to the v1 and v2 docs.

**Comment by CrystalBallBe** [comment]
To make that change, I’m struggling with Jekyll and Liquid. It will take a little more time, so please wait a little longer.
I will ping you when I've finished. @msagansk @MicahZoltu

**Pull request closed without merging**
