### PR TITLE
Update URLs of Augur Discord server

### PR DESCRIPTION
**Pull request by CrystalBallBe**
https://invite.augur.net → https://discord.gg/guXC9Bd4

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I don't believe this is a necessary or desired change.  https://invite.augur.net/ is a redirect to a permanent discord invite link that is more user friendly than a traditional Discord invite link.

What was it that motivated you to make this change @CrystalBallBe?

**Comment by CrystalBallBe** [comment]
@MicahZoltu 
> What was it that motivated you to make this change

I thought I didn't want to rely on the domain `augur.net`. I thought the link would be disabled if `augur.net` was gone.

**Comment by CrystalBallBe** [comment]
Is `https://invite.augur.net` valid if augur.net is closed? If so, I should undo this change.

**Comment by CrystalBallBe** [comment]
I read [this site](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs) to find out how to get a custom invite URL for the Discord server. 
According to the site, you need to partner with Disord or have the highest server boost level (level 3) to get that custom invite URL.
It seems to me that the Augur Discord server doesn't meet either of those requirements.

**Comment by CrystalBallBe** [comment]
I'm not sure how the custom URL for the Augur Discord server was obtained.

**Comment by MicahZoltu** [comment]
We aren't a Discord partner sadly, not enough users.  re: no reliance on augur.net, I would say we can rely on it for now, until such time in the future as it goes down and then we can easily switch to a Discord.gg link.  That way we are resistant to censorship (we have a backup plan in the case of censorship) but we provide users with a nice experience in the meantime.

**Comment by CrystalBallBe** [comment]
OK. I will undo this change tomorrow 🌝

**Comment by CrystalBallBe** [comment]
I undo this change by the PR https://github.com/msagansk/Augur.Guide/pull/41

**Pull request merged**
