### PR TITLE
Add two images to To-do's

### PR DESCRIPTION
**Pull request by CrystalBallBe**
I removed blank lines and added a description of the forking period. Additinally, I added two images which are:
- assets/images/version2-english/fork/to-dos/forking-period.svg
- assets/images/version2-english/fork/to-dos/directions-of-migrating.svg

`forking-period.svg` is:
image

`directions-of-migrating.svg` is:
image

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I like the pictures!

**Comment by CrystalBallBe** [comment]
I'm glad to hear that ☺️

**Comment by CrystalBallBe** [comment]
@MicahZoltu Should I use Check-mark(✅) rather than O-mark(🟢) in the image?
I just remembered that O-mark is used to represent affirmation only in East Asia, while, Check-mark is used in English-speaking countries. I'm making this document for English-speakers. Does even O-mark still make sense to you?

**Comment by MicahZoltu** [comment]
I'm partial to ✔ myself.  😀 

That being said, the green O and red X are clear to me as a native English speaker and I'm fine with keeping them.

**Comment by CrystalBallBe** [comment]
Thanks for the clarification 🌝 I leave the image as it is.

**Pull request merged**
