### PR TITLE
Change for multiple versions and languages

### PR DESCRIPTION
**Pull request by CrystalBallBe**
@msagansk (cc: @MicahZoltu )
In order to support multiple versions and languages, I made the following changes.

---
## Add top-page files
I added a top-page.
screenshot-crystalballbe-github-io-1604036095215

The content file is `root/index.md`, and template file is `root/_layouts/top-page.html`

## Move content files to `collections` folder
I treat each version as `collections`. (Reference: https://jekyllrb.com/docs/collections/)
In order to gather all version's documents in the same place, I added the directory `root/collections`. This directory is defined by the key `collections_dir` which is in `_config.yml`, and I set this key as `collections`.

The documents for version1 are stored in `root/collections/_version1-english/`, and for version2 are stored in `root/collections/_version2-english/`.

`_config.yml` has a key to set whether or not to show the link to contents of a version on the top-page. The key is `collections.versionX-english.top-page`. For example, If I you set `collections.version1-english.top-page` as `false`, then the link to version1 does not appear on the top-page. So I set the value of `collections.version2-english.top-page` to `false` since the documents of version2 are under construction.

`_config.yml` also has a key to create a rendered page for each version's document. The key is `collections.versionX-english.output`. For example, If I you set `collections.version1-english.output` as `false`, then the pages for version1 don`t be created. So I now set the value of `collections.version2-english.output` to `false` for the same reason as above.

## Move image files to folder `version1-english`
I stored image files by version under `root/assets/images/`. Since `favicons` and `logos` are the same in each version, they are not separated into folders.

## Commonize HTML tag
I cut out the tags that reused in the HTML files and saved them as separate files, I stored these files in `root/_include/`.

## Replace hard-corded URL with variable
Some URLs in the original source contained the hard-corded string `https://augur.guide`. So I replaced this with the variable `{{ "/" | absolute_url }}`.  Because I wanted to eliminate the access of `https://augur.guide` when debugging in a local environment. 
When you build this site, this variable is rewritten to the domain root. (For example, if you build on local environment then the variables are rewritten to `http://localhost:4000`, and if on production environment, rewritten to `https://augur.guide`.)

## Change glossary's URL (replace " " with "_")
The URL linking to the glossary contained a space character. Therefore, the space character was replaced with `% 20` in the actual URL. In order to improve readability, I replaced the space character with `_`.
I also replaced the filename from `glossary.md` with `7-glossary.md` to match the naming convention with other content files (e.g. 1-getting-started.md).

## Add plugin "jekyll-seo-tag"
The original file seemed to want to set up SEO. Reference↓
https://github.com/msagansk/Augur.Guide/blob/347c3c2df7b12a1f54e232212715be7a4893df3f/_layouts/default.html#L7
But it seemed that the setting wasn't enough. So I added plugin `jekyll-seo-tag` to `_config.yml`.

## Fix the link to edit page in github
The original was to generate a URL that linked to Github-edit-page by using the variable `github_edit_link` which is provided by Jekyll (Reference: https://github.com/jekyll/github-metadata/blob/master/docs/edit-on-github-link.md). However, when adding `collections`, this variable did not work.

For example, the URL I want to be generated is that:
https://github.com/CrystalBallBe/CrystalBallBe.github.io/edit/master/collections/_version1-english/1-getting-started.md
But the actual URL generated by `github_edit_link` is that:
https://github.com/CrystalBallBe/CrystalBallBe.github.io/edit/master/_version1-english/1-getting-started.md

To see this result, the directory which is defined by `collections_dir` is skipped. So I stopped using the variable and implemented a process that dynamically generated the link.

## Add version information below the logo
This links to the top-page of the version.
under-logo

## Add the last-update date to the bottom of each document.
Getting the latest commit-datetime of the displaying document by using Github API, and added it to the end of the page.
last-update

## Add `Gemfile`
I added `Gemfile` to `root/`. This file is not needed for the production environment, but required for debugging in a local environment.

### CODE REVIEW

**Comment by msagansk** [comment]
Wow, good work! Do you want access to merge your own PRs?

**Comment by CrystalBallBe** [comment]
>Do you want access to merge your own PRs?　

@msagansk If you don't mind, I want.

I don't know how long it will take but I want to complete the documentation for version 2. Therefore I will send pull requests many times. So I think it would be convenient for me (and you?) to have the permission to merge in your repository. But even if I do, I don't want to merge content that no one has checked. I want at least one person to check it before merging.

@MicahZoltu , If I submit a pull request, could you check that when you have time?

**Comment by msagansk** [comment]
Ok I've sent you an invite @CrystalBallBe. I honestly don't think I'll have the time to thoroughly review the PRs so I'm totally ok with you pushing this forward as you want. 

The Augur.Guide domain is paid until January 21. We can discuss what to do with it before then. I may just keep renewing it if this site shows some life for v2.

**Comment by CrystalBallBe** [comment]
Thanks! I'm accepting the invitation.

For that domain, I would be happy to remain Augur.Guide, but I don't mind it being Augur.Guide.github.io.
You may  want to extend the life of the domain if you think it's worth doing so when it expires.

**Pull request merged**
