### PR TITLE
Delete redundant description Restrictions-on-use

### PR DESCRIPTION
**Pull request by CrystalBallBe**
There is no defference between "During a fork" and "After a fork", so I combined them into one.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Maybe name it "before a fork starts" and "after a fork starts" for a bit of additional clarity?  That may result in rendering being messed up for column header name being too long though.

**Comment by CrystalBallBe** [comment]
> Maybe name it "before a fork starts" and "after a fork starts" for a bit of additional clarity? That may result in rendering being messed up for column header name being too long though.

I'll try that and see how it looks. But before that, I'm going to revert this PR to reflect the suggestion https://github.com/msagansk/Augur.Guide/pull/45#issuecomment-763501116

**Comment by CrystalBallBe** [comment]
@MicahZoltu 
I updated the chart 👇 It looks good to me, what do you think?
The Changes are:
 - The header name: `Before a Fork` → `Before a Fork Starts`.
 - The header name: `After a Fork` → `After a Fork Ends`.
 - Added a new line `Migrate REP from Parent to Child` to the bottom.
image

**Comment by MicahZoltu** [comment]
Looks good!

**Comment by MicahZoltu** [comment]
The `-` in the `Child` column of During a Fork and After a Fork Ends is a little weird, since the rest of the column has checks or x.  I think I understand the reasoning for it, and I'm not sure if it would be better or worse to put an `x` in those two slots or not, but I wanted to mention it.

**Comment by CrystalBallBe** [comment]
How about this image?👇 I merged cells at the bottom line.
image

**Comment by MicahZoltu** [comment]
Works for me.

**Pull request merged**
